Skip NaN and Inf test on MSVC
 When I try execute unit tests on MSVC a compiler error is reported:
 "C:\Users\Uilian Ries\Development\parson\tests.c(441):
  error C2124: divide or mod by zero [C:\Users\Uilian Ries\
  Development\parson\build\test-all.vcxproj]"

 MSVC does not support/accept divide or mod by zero

 More details: https://msdn.microsoft.com/en-us/library/byc7w2kb.aspx

Signed-off-by: Uilian Ries <uilianries@gmail.com>